# Generated by cucumber-sinatra. (2014-10-13 11:21:40 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/map_to_the_future.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = MapToTheFuture

class MapToTheFutureWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  MapToTheFutureWorld.new
end
