# Generated by cucumber-sinatra. (2014-10-13 11:21:40 +0100)

ENV['RACK_ENV'] = 'Test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/server.rb')

require 'capybara'
require 'capybara/cucumber'
require 'capybara/poltergeist'
require 'rspec'

Capybara.app = MapToTheFuture
Capybara.register_driver :poltergeist do |app|
  Capybara::Poltergeist::Driver.new(app, {
    js_errors: false
  })
end
Capybara.javascript_driver = :poltergeist
Capybara.default_wait_time = 3

Capybara.register_driver :selenium do |app|
  Capybara::Selenium::Driver.new(app, :browser => :chrome)
end

class MapToTheFutureWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  MapToTheFutureWorld.new
end
